# Personal website title
website_title: "Cat"

# choose your intentional page style
website_style:
  - "default"
  - "dark"
  - "light"

# website global icons
icons: []


# page part
pages:
  # about page, here you can modify
  about:
    icons:
      - "/path/to/icon"

    widgets:
      - "path/to/widget1"
      - "path/to/widget2"

    contents:
      first_paragraph:
        title:
          - "Hello, World1"
        content:
          - "Hello, World1"

      second_paragraph:
        title:
          - "Hello, World2"
        content:
          - "Hello, World2"

      Third_paragraph:
        title:
          - "Hello, World3"
        content:
          - "Hello, World3"
  # skill page
  skill:
    icons: ""
    widgets: ""

  #
  research:
    icons: ""
    widgets: ""
  more:
    icons: ""
    widgets: ""
